### ISSUE TITLE
Feature request. For Windows 10 add to context menu Items for Windows Terminal

### ISSUE THREAD

**Issue by carloscondit** [martinstoeckli/ExplorerGenie#6]
Hi! Is it possible to add to the context menu items for Windows Terminal? As done [here.](https://github.com/lextm/windowsterminal-shell#powershell-scripts-to-installuninstall-context-menu-items-for-windows-terminal)

**Comment by martinstoeckli** [comment]
Hello @carloscondit
I had a quick glance at the project, but I'm not sure what the real advantage of this Windows Terminal is, what makes it different from the built in tools? By looking at the screenshots it looks as if it is a replacement of command line and powershell, or why are there submenu items "Windows Terminal here\cmd" and "Windows Terminal here\PowerShell", isn't the Windows Terminal a tool on its own?

**Comment by carloscondit** [comment]
Hello @martinstoeckli
I am afraid to mislead you. You'd better read the description of this product yourself.
[Terminal & Console Overview](https://github.com/microsoft/terminal#terminal--console-overview)
Here's a short description from there: _"Windows Terminal is a new, modern, feature-rich, productive terminal application for command-line users. It includes many of the features most frequently requested by the Windows command-line community including support for tabs, rich text, globalization, configurability, theming & styling, and more."_

And if possible, then try to work in this application.

**Comment by martinstoeckli** [comment]
You didn't mislead me, I already read the linked explanation. I try to decide if this tool could be of common interest, or if the benefit of installing this terminal is too small and it is used only by a few users.

Adding a context menu to open tools can be done without installing ExplorerGenie, just by editing the registry. This way you can add whatever commands you need and don't need to install an extension at all, have a look at this example:

  https://petri.com/add-powershell-windows-explorer-context-menu-windows-10

I already thought about publishing such registry examples on my homepage, so users can use them as template and have an alternative to installing ExplorerGenie.

**Comment by carloscondit** [comment]
I was able to confuse both you and myself. It turns out that the option is already in the context menu. But it allows you to open the folder only with user rights. And it would be great if you decided to add opening in Microsoft Terminal (also with administrator rights) as an option. In any case, I recommend that you use the Microsoft Terminal program. You should like it. 
This issue can be closed. Thanks for your work and good luck!

![wt](https://user-images.githubusercontent.com/39201353/104119914-f861b800-5343-11eb-8acf-23cc118bd344.png)

**Comment by martinstoeckli** [comment]
I'm working on custom menu items, which can be added to open user defined tools. This should allow to open the Windows Terminal as well.

**Comment by carloscondit** [comment]
Great news! Thank you!

**Comment by martinstoeckli** [comment]
The just published version 2.0.0 allows to add user defined menu entries for the "goto tool" command, this should make it possible to open the Windows Terminal.
